myblog/blog/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import *

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('login/', Login.as_view(), name='login'),
    path('profile/<int:pk>', Profile.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('delete/<int:user_id>', delete, name='delete'),
    path('update/<int:pk>', UserView.as_view(), name='update'),
    path('profile/<int:pk>/post/create', PostCreate.as_view(), name='post_create'),
    path('profile/<int:pk>/comment/create/<int:post_id>', CommentCreate.as_view(), name='comment_create'),
    path('profile/<int:pk>/comment/commented/create/<int:comment_id>', CommentCommentedView.as_view(), name='comment_commented'),
    path('comment/update/<int:pk>', CommentUpdate.as_view(), name='comment_update'),
    path('comment/delete/<int:comment_id>', delete_comment, name='comment_delete'),
    path('comment/commented/update/<int:pk>', CommentCommentedUpdate.as_view(), name='comment_commented_update'),
    path('comment/commented/delete/<int:comment_id>', delete_comment_commented, name='delete_comment_commented'),
]

myblog/myblog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/blog/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    name = models.CharField(max_length=254, verbose_name='Имя', blank=False)
    surname = models.CharField(max_length=254, verbose_name='Фамилия', blank=False)
    username = models.CharField(max_length=254, verbose_name='Логин', blank=False, unique=True)
    email = models.EmailField(verbose_name='Почта', blank=False, unique=True)
    password = models.CharField(max_length=254, verbose_name='Пароль', blank=False)
    avatar = models.ImageField(verbose_name='Аватар', upload_to='photo', null=True, blank=True)

    def __str__(self):
        return f"{self.name} {self.surname}"


class Post(models.Model):
    name = models.CharField(max_length=254, verbose_name='Название поста', blank=False)
    content = models.TextField(verbose_name='Контент', blank=False, null=False)
    photo = models.ImageField(verbose_name='Фото к посту', upload_to='photo', null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')

    def __str__(self):
        return self.name


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=254, verbose_name='Комментарий', blank=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Название поста', null=False)
    photo = models.ImageField(verbose_name='Фото комментария', upload_to='photo', null=True, blank=True)

    def __str__(self):
        return self.content


class UserPosted(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)


class CommentCommented(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    content = models.CharField(max_length=254, verbose_name='Комментарий', blank=False)
    photo = models.ImageField(verbose_name='Фото комментария', upload_to='photo', null=True, blank=True)

    def __str__(self):
        return self.content

myblog/blog/forms.py
from django import forms
from django.contrib.auth.hashers import make_password
from .models import *


class UserForm(forms.ModelForm):

    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data["password"]
        if password:
            user.password = make_password(password)
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['name', 'surname', 'username', 'email', 'password', 'avatar']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['name', 'content', 'photo']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content', 'photo']


class CommentCommentForm(forms.ModelForm):
    class Meta:
        model = CommentCommented
        fields = ['content', 'photo']

myblog/blog/views.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import *
from .forms import *
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'blog/index.html'
    model = Post
    paginate_by = 10
    ordering = ['-date']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        posts = Post.objects.all().order_by('-date')
        paginator = Paginator(posts, self.paginate_by)
        page = self.request.GET.get('page')

        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)

        context['posts'] = posts
        context['comment_form'] = CommentForm()
        context['comment_comment_form'] = CommentCommentForm()
        return context


class Login(LoginView):
    template_name = 'blog/login.html'


class Profile(LoginRequiredMixin, TemplateView):
    template_name = 'blog/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = User.objects.get(pk=self.kwargs.get('pk'))
        user_posted = UserPosted.objects.filter(user=self.kwargs.get('pk')).values_list('post', flat=True)
        posts = Post.objects.filter(pk__in=user_posted)
        user_commented = Comment.objects.filter(post_id__in=posts.values_list('id', flat=True))

        context['user_commented'] = user_commented
        context['profile'] = profile
        context['posts'] = posts
        context['post_form'] = PostForm()
        context['comment_form'] = CommentForm()
        context['comment_comment_form'] = CommentCommentForm()
        return context


def delete(request, user_id):
    user = User.objects.get(id=user_id)
    if request.method == 'POST':
        user.delete()
        return redirect(reverse('home'))


class UserView(UpdateView):
    template_name = 'blog/update.html'
    model = User
    form_class = UserForm

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        response = super().form_valid(form)
        self.object = form.save()
        update_session_auth_hash(self.request, self.object)
        return response

    def get_success_url(self):
        return reverse('profile', args=[self.kwargs['pk']])


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        post = form.save(commit=False)
        post.user = self.request.user
        post.save()

        user_posted = UserPosted.objects.create(post=post, user=self.request.user)
        user_posted.save()

        return redirect(reverse('profile', kwargs={'pk': self.request.user.pk}))


class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post_id = self.kwargs['post_id']
        comment.user = self.request.user
        comment.save()
        if 'profile_id' in self.kwargs:
            return redirect(reverse('profile', kwargs={'pk': self.kwargs['profile_id']}))
        else:
            return redirect('home')


class CommentCommentedView(LoginRequiredMixin, CreateView):
    model = CommentCommented
    form_class = CommentCommentForm

    def form_valid(self, form):
        comment_comment = form.save(commit=False)
        comment_id = self.kwargs['pk']
        comment_comment.comment = Comment.objects.get(id=comment_id)
        comment_comment.user = self.request.user
        comment_comment.save()

        if 'profile_id' in self.kwargs:
            return redirect(reverse('profile', kwargs={'pk': self.kwargs['profile_id']}))
        else:
            return redirect('home')


class CommentUpdate(UpdateView):
    template_name = 'blog/update_comment.html'
    model = Comment
    form_class = CommentForm

    def get_success_url(self):
        if 'profile_id' in self.kwargs:
            return reverse('profile', kwargs={'pk': self.kwargs['profile_id']})
        else:
            return reverse('home')


def delete_comment(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    if request.method == 'POST':
        comment.delete()
        return redirect(reverse('home'))


class CommentCommentedUpdate(UpdateView):
    template_name = 'blog/comment_commented_update.html'
    model = CommentCommented
    form_class = CommentCommentForm

    def get_success_url(self):
        if 'profile_id' in self.kwargs:
            return reverse('profile', kwargs={'pk': self.kwargs['profile_id']})
        else:
            return reverse('home')


def delete_comment_commented(request, comment_id):
    comment = CommentCommented.objects.get(id=comment_id)
    if request.method == 'POST':
        comment.delete()
        return redirect(reverse('home'))

myblog/blog/templates/blog/comment_commented_update.html
{% extends 'base.html' %}

{% block content %}
    <h3>Редактирование ответа на комментарий</h3>
    <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Изменить комментарий">
    </form>
{% endblock %}

myblog/blog/templates/blog/index.html
{% extends 'base.html' %}

{% block title%}Авторизация{% endblock%}

{% block content %}
{% for post in posts %}
        <div>

            <h4>{{ post.name }}</h4>
            <p>{{ post.content }}</p>
            {% if post.photo %}
                <img src="{{ post.photo.url }}" alt="Фото поста" style="max-height: 100px;">
            {% endif %}

            <h5>Комментарии:</h5>
            <form action="{% url 'comment_create' user.id post.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="post.id" value="{{ post.id }}">
                {{ comment_form.as_p }}
                <button type="submit" id="{{ post.id }}">Комментировать</button>
            </form>


                    <ul>
                        {% for comment in post.comment_set.all %}

                            <div>
                                <li>{{ comment.content }}
                                    {% if comment.photo %}
                                        <img src="{{ comment.photo.url }}" alt="Фото комментария" style="max-height: 100px;">
                                    {% endif %}
                                    {% if comment.user == request.user %}
                                        <a href="{% url 'comment_update' comment.id %}">Редактировать комментарий</a>
                                        <button type="submit" id="comment1_{{ comment.id }}" onclick="Btn('{{ comment.id }}')">Удалить комментарий</button>
                                        <form action="{% url 'comment_delete' comment.id %}" method="POST" id="comment2_{{ comment.id }}" style="display: none">
                                            {% csrf_token %}
                                            <button type="submit">Подтвердить удаление</button>
                                        </form>
                                    {% endif %}
                                </li>
                            </div>


                            <br>

                                <ul>
                                    {% for comment_commented in comment.commentcommented_set.all %}
                                        <div>
                                            <li>{{ comment_commented.content }}
                                                {% if comment_commented.photo %}
                                                    <img src="{{ comment_commented.photo.url }}" alt="Фото комментария" style="max-height: 100px;">
                                                {% endif %}
                                                {% if comment_commented.user == request.user %}
                                                    <a href="{% url 'comment_commented_update' comment_commented.id %}">Редактировать комментарий</a>

                                                    <button type="submit" id="commented1_{{ comment_commented.id }}" onclick="Btn1('{{ comment_commented.id }}')">Удалить комментарий</button>
                                                    <form action="{% url 'delete_comment_commented' comment_commented.id %}" method="POST" id="commented2_{{ comment_commented.id }}" style="display: none">
                                                        {% csrf_token %}
                                                        <button type="submit">Подтвердить удаление</button>
                                                    </form>
                                                {% endif %}
                                            </li>
                                        </div>
                                    {% endfor %}
                                </ul>


                            <div>
                                <h6>Ответить на комментарий:</h6>
                                <form action="{% url 'comment_commented' comment.id user.id %}" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <input type="hidden" name="comment.id" value="{{ comment.id }}">
                                    {{ comment_comment_form.as_p }}
                                    <button type="submit" id="{{ comment.id }}">Комментировать</button>
                                </form>
                            </div>

                        {% endfor %}
                    </ul>

        </div>

        <br>
    {% endfor %}


<div>
    <span>
        {% if posts.has_previous %}
            <a href="?page=1">&laquo; первая</a>
            <a href="?page={{ posts.previous_page_number }}">предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ posts.number }} из {{ posts.paginator.num_pages }}.
        </span>

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">следующая</a>
            <a href="?page={{ posts.paginator.num_pages }}">последняя &raquo;</a>
        {% endif %}
    </span>
</div>
        {% for i in commented %}
            <p>{{ i.content }}</p>
            {% if i.photo %}
                <img src="{{ i.photo.url }}" alt="Фото комментария" style="max-height: 100px;">
            {% endif %}
        {% endfor %}

    <script>
        function Btn(commentId) {
            document.getElementById('comment1_' + commentId).style.display = 'none';
            document.getElementById('comment2_' + commentId).style.display = 'block';
        }

        function Btn1(commentedId) {
            document.getElementById('commented1_' + commentedId).style.display = 'none';
            document.getElementById('commented2_' + commentedId).style.display = 'block';
        }
    </script>

{% endblock %}

myblog/blog/templates/blog/login.html
{% extends 'base.html' %}

{% block content %}
    <h3>Аутентификация</h3>
    {% if form.errors %}
        <div>
            <p class="p-1">Не правильный логин или пароль</p>
        </div>
    {% endif %}
    {% if user.is_authenticated %}
        <p>Вы уже авторизированы.</p>
    {% else %}
        <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            <table>
                <tr>
                    <td>{{ form.username.label_tag }}</td>
                    <td>{{ form.username }}</td>
                </tr>
                <tr>
                    <td>{{ form.password.label_tag }}</td>
                    <td>{{ form.password }}</td>
                </tr>
            </table>
            <input type="submit" value="Войти">
        </form>
    {% endif %}
{% endblock %}

myblog/blog/templates/blog/profile.html
{% extends 'base.html' %}

{% block content %}
    <h3>Привет {{ profile.username }}</h3>
    {% if profile.avatar %}
        <img style="max-height: 50px;" src="{{ profile.avatar.url }}" alt="Аватар">
    {% else %}
        <img style="max-height: 50px;" src="/files/photo/default.jpg" alt="Аватар дефолтный">
    {% endif %}
    <p>Ваше имя: {{ profile.name }}</p>
    <p>Ваша фамилия: {{ profile.surname }}</p>
    <p>Ваш логин: {{ profile.username }}</p>
    <a href="{% url 'update' profile.pk %}">Редактировать профиль</a>
    <button type="submit" id="1" onclick="Btn()">Удалить профиль</button>
    <form action="{% url 'delete' profile.id %}" method="POST" id="2" style="display: none">
        {% csrf_token %}
        <button type="submit">Подтвердить удаление</button>
    </form>

    <br>

    <h3>Создать пост</h3>
    <form action="{% url 'post_create' profile.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ post_form.as_p }}
        <button type="submit">Создать</button>
    </form>

    <br>

    {% for post in posts %}
        <div>

            <h4>{{ post.name }}</h4>
            <p>{{ post.content }}</p>
            {% if post.photo %}
                <img src="{{ post.photo.url }}" alt="Фото поста" style="max-height: 100px;">
            {% endif %}

            <h5>Комментарии:</h5>
            <form action="{% url 'comment_create' profile.id post.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="post.id" value="{{ post.id }}">
                {{ comment_form.as_p }}
                <button type="submit" id="{{ post.id }}">Комментировать</button>
            </form>


                    <ul>
                        {% for comment in post.comment_set.all %}

                            <div>
                                <li>{{ comment.content }}
                                    {% if comment.photo %}
                                        <img src="{{ comment.photo.url }}" alt="Фото комментария" style="max-height: 100px;">
                                    {% endif %}
                                </li>
                            </div>


                            <br>

                                <ul>
                                    {% for comment_commented in comment.commentcommented_set.all %}
                                        <div>
                                            <li>{{ comment_commented.content }}
                                                {% if comment_commented.photo %}
                                                    <img src="{{ comment_commented.photo.url }}" alt="Фото комментария" style="max-height: 100px;">
                                                {% endif %}
                                            </li>
                                        </div>
                                    {% endfor %}
                                </ul>


                            <div>
                                <h6>Ответить на комментарий:</h6>
                                <form action="{% url 'comment_commented' comment.id profile.id %}" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <input type="hidden" name="comment.id" value="{{ comment.id }}">
                                    {{ comment_comment_form.as_p }}
                                    <button type="submit" id="{{ comment.id }}">Комментировать</button>
                                </form>
                            </div>

                        {% endfor %}
                    </ul>

        </div>

        <br>
    {% endfor %}

    <script>
        function Btn() {
            document.getElementById('1').style.display = 'none';
            document.getElementById('2').style.display = 'block';
        }
    </script>
{% endblock %}

myblog/blog/templates/blog/update.html
{% extends 'base.html' %}

{% block content %}
    <h3>Редактирование профиля</h3>
    <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Изменить профиль">
    </form>
{% endblock %}

myblog/blog/templates/blog/update_comment.html
{% extends 'base.html' %}

{% block content %}
    <h3>Редактирование комментария</h3>
    <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Изменить комментарий">
    </form>
{% endblock %}